pring:
  social:
    facebook:
      app-id: 962223610477458
      app-secret: b7dfec28b08ac4e8c2a09cbac4662c15
    twitter:
      app-id: fV5y7Lf8NSyf4TzeGSz7ZKwRf
      app-secret: 1vzxsfuX7AkCaMasvhStHesOAB6pE0sePg8m55NpWhYrhJNUld